'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class es_MX
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CS540_Group_Project.es-MX", GetType(es_MX).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to agregue pollo asado para.
        '''</summary>
        Friend Shared ReadOnly Property addSalad() As String
            Get
                Return ResourceManager.GetString("addSalad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property addSaladprice() As String
            Get
                Return ResourceManager.GetString("addSaladprice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (3) for 3.50.
        '''</summary>
        Friend Shared ReadOnly Property app1price1() As String
            Get
                Return ResourceManager.GetString("app1price1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (6) for 6.99.
        '''</summary>
        Friend Shared ReadOnly Property app1price2() As String
            Get
                Return ResourceManager.GetString("app1price2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (12) for 13.50.
        '''</summary>
        Friend Shared ReadOnly Property app1price3() As String
            Get
                Return ResourceManager.GetString("app1price3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 8.99.
        '''</summary>
        Friend Shared ReadOnly Property app2price() As String
            Get
                Return ResourceManager.GetString("app2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 7.99.
        '''</summary>
        Friend Shared ReadOnly Property app3price() As String
            Get
                Return ResourceManager.GetString("app3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.99.
        '''</summary>
        Friend Shared ReadOnly Property app4price() As String
            Get
                Return ResourceManager.GetString("app4price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to APERITIVOS.
        '''</summary>
        Friend Shared ReadOnly Property appetizer0() As String
            Get
                Return ResourceManager.GetString("appetizer0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nudos de ajo.
        '''</summary>
        Friend Shared ReadOnly Property appetizer1() As String
            Get
                Return ResourceManager.GetString("appetizer1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to servido con salsa marinara.
        '''</summary>
        Friend Shared ReadOnly Property appetizer1d() As String
            Get
                Return ResourceManager.GetString("appetizer1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alas deshuesadas.
        '''</summary>
        Friend Shared ReadOnly Property appetizer2() As String
            Get
                Return ResourceManager.GetString("appetizer2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ofertas de pollo frito servido con su elección de salsa (suave, medio, caliente, ajo Parmesean, barbacoa, jalapeño frambuesa, ajo picante, pimienta de limón).
        '''</summary>
        Friend Shared ReadOnly Property appetizer2d() As String
            Get
                Return ResourceManager.GetString("appetizer2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Albóndigas.
        '''</summary>
        Friend Shared ReadOnly Property appetizer3() As String
            Get
                Return ResourceManager.GetString("appetizer3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to casero servido con salsa marinara.
        '''</summary>
        Friend Shared ReadOnly Property appetizer3d() As String
            Get
                Return ResourceManager.GetString("appetizer3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Papas fritas.
        '''</summary>
        Friend Shared ReadOnly Property appetizer4() As String
            Get
                Return ResourceManager.GetString("appetizer4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to papas fritas condimentadas, servidas con ketchup.
        '''</summary>
        Friend Shared ReadOnly Property appetizer4d() As String
            Get
                Return ResourceManager.GetString("appetizer4d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QUESO.
        '''</summary>
        Friend Shared ReadOnly Property cheese0() As String
            Get
                Return ResourceManager.GetString("cheese0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ricotta.
        '''</summary>
        Friend Shared ReadOnly Property cheese1() As String
            Get
                Return ResourceManager.GetString("cheese1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property cheese1price() As String
            Get
                Return ResourceManager.GetString("cheese1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to queso Provolone.
        '''</summary>
        Friend Shared ReadOnly Property cheese2() As String
            Get
                Return ResourceManager.GetString("cheese2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property cheese2price() As String
            Get
                Return ResourceManager.GetString("cheese2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to queso azul.
        '''</summary>
        Friend Shared ReadOnly Property cheese3() As String
            Get
                Return ResourceManager.GetString("cheese3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property cheese3price() As String
            Get
                Return ResourceManager.GetString("cheese3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to queso mozzarella extra.
        '''</summary>
        Friend Shared ReadOnly Property cheese4() As String
            Get
                Return ResourceManager.GetString("cheese4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property cheese4price() As String
            Get
                Return ResourceManager.GetString("cheese4price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to queso de cabra.
        '''</summary>
        Friend Shared ReadOnly Property cheese5() As String
            Get
                Return ResourceManager.GetString("cheese5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property cheese5price() As String
            Get
                Return ResourceManager.GetString("cheese5price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREE SU PROPIA EMPANADA.
        '''</summary>
        Friend Shared ReadOnly Property createPizza() As String
            Get
                Return ResourceManager.GetString("createPizza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10 inch cheese pizza 9.99.
        '''</summary>
        Friend Shared ReadOnly Property createPizzaprice1() As String
            Get
                Return ResourceManager.GetString("createPizzaprice1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 18 inch cheese pizza 18.99.
        '''</summary>
        Friend Shared ReadOnly Property createPizzaprice2() As String
            Get
                Return ResourceManager.GetString("createPizzaprice2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MENÚ COMPLETO SERVIDO DE 11 a.m.-9 p.m. ENTREGA RÁPIDA | PIZZA SERVIDA TODO EL DÍA, TODOS LOS DÍAS.
        '''</summary>
        Friend Shared ReadOnly Property description() As String
            Get
                Return ResourceManager.GetString("description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5.99.
        '''</summary>
        Friend Shared ReadOnly Property desser1price() As String
            Get
                Return ResourceManager.GetString("desser1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to POSTRES.
        '''</summary>
        Friend Shared ReadOnly Property dessert0() As String
            Get
                Return ResourceManager.GetString("dessert0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tarta de queso.
        '''</summary>
        Friend Shared ReadOnly Property dessert1() As String
            Get
                Return ResourceManager.GetString("dessert1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to relleno de crema de queso, corteza de Graham Cracker.
        '''</summary>
        Friend Shared ReadOnly Property dessert1d() As String
            Get
                Return ResourceManager.GetString("dessert1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pastel de mousse de chocolate.
        '''</summary>
        Friend Shared ReadOnly Property dessert2() As String
            Get
                Return ResourceManager.GetString("dessert2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mousse de chocolate, crema batida, corteza de galleta de chocolate.
        '''</summary>
        Friend Shared ReadOnly Property dessert2d() As String
            Get
                Return ResourceManager.GetString("dessert2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5.99.
        '''</summary>
        Friend Shared ReadOnly Property dessert2price() As String
            Get
                Return ResourceManager.GetString("dessert2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fudge Brownie.
        '''</summary>
        Friend Shared ReadOnly Property dessert3() As String
            Get
                Return ResourceManager.GetString("dessert3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.99.
        '''</summary>
        Friend Shared ReadOnly Property dessert3price() As String
            Get
                Return ResourceManager.GetString("dessert3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CENAS.
        '''</summary>
        Friend Shared ReadOnly Property dinner0() As String
            Get
                Return ResourceManager.GetString("dinner0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to all dinners are served with 2 garlic knots.
        '''</summary>
        Friend Shared ReadOnly Property dinner0d() As String
            Get
                Return ResourceManager.GetString("dinner0d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pollo parmesano.
        '''</summary>
        Friend Shared ReadOnly Property dinner1() As String
            Get
                Return ResourceManager.GetString("dinner1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to topped with mozzarella cheese, served with penne pasta, tossed in our homemade marinara sauce, fresh basil, parmesan cheese.
        '''</summary>
        Friend Shared ReadOnly Property dinner1d() As String
            Get
                Return ResourceManager.GetString("dinner1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11.99.
        '''</summary>
        Friend Shared ReadOnly Property dinner1price() As String
            Get
                Return ResourceManager.GetString("dinner1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lasaña de carne.
        '''</summary>
        Friend Shared ReadOnly Property dinner2() As String
            Get
                Return ResourceManager.GetString("dinner2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to prepared with our homemade meatball, sausage, ricotte, parmesan cheese, baked to perfection!.
        '''</summary>
        Friend Shared ReadOnly Property dinner2d() As String
            Get
                Return ResourceManager.GetString("dinner2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11.99.
        '''</summary>
        Friend Shared ReadOnly Property dinner2price() As String
            Get
                Return ResourceManager.GetString("dinner2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pasta penne.
        '''</summary>
        Friend Shared ReadOnly Property dinner3() As String
            Get
                Return ResourceManager.GetString("dinner3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to add 2 meatballs for $3.
        '''</summary>
        Friend Shared ReadOnly Property dinner3add() As String
            Get
                Return ResourceManager.GetString("dinner3add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to homemade marinara sauce, fresh basil, parmesan cheese.
        '''</summary>
        Friend Shared ReadOnly Property dinner3d() As String
            Get
                Return ResourceManager.GetString("dinner3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 8.99.
        '''</summary>
        Friend Shared ReadOnly Property dinner3price() As String
            Get
                Return ResourceManager.GetString("dinner3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hornea Penne Pasta con salchicha.
        '''</summary>
        Friend Shared ReadOnly Property dinner4() As String
            Get
                Return ResourceManager.GetString("dinner4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to homemade marinara sauce, fresh basil, ricotta, parmesan cheese topped with mozzarella.
        '''</summary>
        Friend Shared ReadOnly Property dinner4d() As String
            Get
                Return ResourceManager.GetString("dinner4d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11.99.
        '''</summary>
        Friend Shared ReadOnly Property dinner4price() As String
            Get
                Return ResourceManager.GetString("dinner4price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BEBIDAS.
        '''</summary>
        Friend Shared ReadOnly Property drink0() As String
            Get
                Return ResourceManager.GetString("drink0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Toro rojo.
        '''</summary>
        Friend Shared ReadOnly Property drink1() As String
            Get
                Return ResourceManager.GetString("drink1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.99.
        '''</summary>
        Friend Shared ReadOnly Property drink1price() As String
            Get
                Return ResourceManager.GetString("drink1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to zico agua de coco.
        '''</summary>
        Friend Shared ReadOnly Property drink2() As String
            Get
                Return ResourceManager.GetString("drink2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property drink2price() As String
            Get
                Return ResourceManager.GetString("drink2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to agua embotellada.
        '''</summary>
        Friend Shared ReadOnly Property drink3() As String
            Get
                Return ResourceManager.GetString("drink3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.29.
        '''</summary>
        Friend Shared ReadOnly Property drink3price() As String
            Get
                Return ResourceManager.GetString("drink3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 20 g de soda.
        '''</summary>
        Friend Shared ReadOnly Property drink4() As String
            Get
                Return ResourceManager.GetString("drink4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.25.
        '''</summary>
        Friend Shared ReadOnly Property drink4prince() As String
            Get
                Return ResourceManager.GetString("drink4prince", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to agua vitaminada.
        '''</summary>
        Friend Shared ReadOnly Property drink5() As String
            Get
                Return ResourceManager.GetString("drink5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.29.
        '''</summary>
        Friend Shared ReadOnly Property drink5price() As String
            Get
                Return ResourceManager.GetString("drink5price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PROTEÍNA.
        '''</summary>
        Friend Shared ReadOnly Property protein0() As String
            Get
                Return ResourceManager.GetString("protein0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pepperoni.
        '''</summary>
        Friend Shared ReadOnly Property protein1() As String
            Get
                Return ResourceManager.GetString("protein1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property protein1price() As String
            Get
                Return ResourceManager.GetString("protein1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to salchicha.
        '''</summary>
        Friend Shared ReadOnly Property protein2() As String
            Get
                Return ResourceManager.GetString("protein2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property protein2price() As String
            Get
                Return ResourceManager.GetString("protein2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to albóndiga.
        '''</summary>
        Friend Shared ReadOnly Property protein3() As String
            Get
                Return ResourceManager.GetString("protein3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property protein3price() As String
            Get
                Return ResourceManager.GetString("protein3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to jamón.
        '''</summary>
        Friend Shared ReadOnly Property protein4() As String
            Get
                Return ResourceManager.GetString("protein4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property protein4price() As String
            Get
                Return ResourceManager.GetString("protein4price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tocino.
        '''</summary>
        Friend Shared ReadOnly Property protein5() As String
            Get
                Return ResourceManager.GetString("protein5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property protein5price() As String
            Get
                Return ResourceManager.GetString("protein5price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pollo asado.
        '''</summary>
        Friend Shared ReadOnly Property protein6() As String
            Get
                Return ResourceManager.GetString("protein6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property protein6price() As String
            Get
                Return ResourceManager.GetString("protein6price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PAPAS ROJAS.
        '''</summary>
        Friend Shared ReadOnly Property redPies0() As String
            Get
                Return ResourceManager.GetString("redPies0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amantes de la carne.
        '''</summary>
        Friend Shared ReadOnly Property redPies1() As String
            Get
                Return ResourceManager.GetString("redPies1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mozzarella, salchichón, salchicha, tocino, jamón, albóndiga.
        '''</summary>
        Friend Shared ReadOnly Property redPies1d() As String
            Get
                Return ResourceManager.GetString("redPies1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amantes vegetarianos.
        '''</summary>
        Friend Shared ReadOnly Property redPies2() As String
            Get
                Return ResourceManager.GetString("redPies2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to espinaca, pimiento verde, tomate, mozzarella, champiñón, cebolla, aceituna, ajo fresco.
        '''</summary>
        Friend Shared ReadOnly Property redPies2d() As String
            Get
                Return ResourceManager.GetString("redPies2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hawaiano.
        '''</summary>
        Friend Shared ReadOnly Property redPies3() As String
            Get
                Return ResourceManager.GetString("redPies3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to piña, jamón, tocino, mozzarella.
        '''</summary>
        Friend Shared ReadOnly Property redPies3d() As String
            Get
                Return ResourceManager.GetString("redPies3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4 Queso.
        '''</summary>
        Friend Shared ReadOnly Property redPies4() As String
            Get
                Return ResourceManager.GetString("redPies4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to parmesano, mozzarella, provolone, ricotta.
        '''</summary>
        Friend Shared ReadOnly Property redPies4d() As String
            Get
                Return ResourceManager.GetString("redPies4d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Especial de Ciro.
        '''</summary>
        Friend Shared ReadOnly Property redPies5() As String
            Get
                Return ResourceManager.GetString("redPies5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to salchichón, salchicha, champiñón, pimiento verde, cebolla, queso extra.
        '''</summary>
        Friend Shared ReadOnly Property redPies5d() As String
            Get
                Return ResourceManager.GetString("redPies5d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rúcula.
        '''</summary>
        Friend Shared ReadOnly Property salad1() As String
            Get
                Return ResourceManager.GetString("salad1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pasas doradas, nueces confitadas, tomate cherry, queso de cabra.
        '''</summary>
        Friend Shared ReadOnly Property salad1d() As String
            Get
                Return ResourceManager.GetString("salad1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5.99/10.00.
        '''</summary>
        Friend Shared ReadOnly Property salad1price() As String
            Get
                Return ResourceManager.GetString("salad1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to César.
        '''</summary>
        Friend Shared ReadOnly Property salad2() As String
            Get
                Return ResourceManager.GetString("salad2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to corazones de romaine, crutones, parmesean afeitado, aderezo caeser clásico.
        '''</summary>
        Friend Shared ReadOnly Property salad2d() As String
            Get
                Return ResourceManager.GetString("salad2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4.99/7.99.
        '''</summary>
        Friend Shared ReadOnly Property salad2price() As String
            Get
                Return ResourceManager.GetString("salad2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verduras mixtas.
        '''</summary>
        Friend Shared ReadOnly Property salad3() As String
            Get
                Return ResourceManager.GetString("salad3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to verduras mixtas, tomate, aceituna negra, pimiento verde, cebolla.
        '''</summary>
        Friend Shared ReadOnly Property salad3d() As String
            Get
                Return ResourceManager.GetString("salad3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4.99/7.99.
        '''</summary>
        Friend Shared ReadOnly Property salad3price() As String
            Get
                Return ResourceManager.GetString("salad3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ENSALADAS.
        '''</summary>
        Friend Shared ReadOnly Property salads0() As String
            Get
                Return ResourceManager.GetString("salads0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (pequeño grande).
        '''</summary>
        Friend Shared ReadOnly Property saladSize() As String
            Get
                Return ResourceManager.GetString("saladSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SALSA.
        '''</summary>
        Friend Shared ReadOnly Property sauce0() As String
            Get
                Return ResourceManager.GetString("sauce0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to rojo.
        '''</summary>
        Friend Shared ReadOnly Property sauce1() As String
            Get
                Return ResourceManager.GetString("sauce1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pesto.
        '''</summary>
        Friend Shared ReadOnly Property sauce2() As String
            Get
                Return ResourceManager.GetString("sauce2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 7.99.
        '''</summary>
        Friend Shared ReadOnly Property sginatureSub1price() As String
            Get
                Return ResourceManager.GetString("sginatureSub1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property sginatureSub2price() As String
            Get
                Return ResourceManager.GetString("sginatureSub2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property sginatureSub3price() As String
            Get
                Return ResourceManager.GetString("sginatureSub3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SIGNATURE SUBS.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub0() As String
            Get
                Return ResourceManager.GetString("signatureSub0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filete de queso.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub1() As String
            Get
                Return ResourceManager.GetString("signatureSub1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡nuestro cheesesteak incluye bistec a la parrilla de primera calidad, queso americano blanco derretido, champiñones, cebollas o pimientos picantes por $ 0.25 cada uno para condimentarlo!.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub1d() As String
            Get
                Return ResourceManager.GetString("signatureSub1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pollo parmesano.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub2() As String
            Get
                Return ResourceManager.GetString("signatureSub2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pollo empanizado casero, queso mozzarella, parmesean rallado, salsa marinara.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub2d() As String
            Get
                Return ResourceManager.GetString("signatureSub2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Albóndigas de Parmesano.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub3() As String
            Get
                Return ResourceManager.GetString("signatureSub3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to nuestra receta de albóndigas casera, cubierta con queso mozzarella, parmesean rallado, salsa marinara.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub3d() As String
            Get
                Return ResourceManager.GetString("signatureSub3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10 inch 11.99.
        '''</summary>
        Friend Shared ReadOnly Property specialtyPizzaprice1() As String
            Get
                Return ResourceManager.GetString("specialtyPizzaprice1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 18 inch 23.99.
        '''</summary>
        Friend Shared ReadOnly Property specialtyPizzaprice2() As String
            Get
                Return ResourceManager.GetString("specialtyPizzaprice2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PIZZAS ESPECIALIZADAS.
        '''</summary>
        Friend Shared ReadOnly Property specialtyPizzas() As String
            Get
                Return ResourceManager.GetString("specialtyPizzas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to STROMBOLI.
        '''</summary>
        Friend Shared ReadOnly Property stromboli0() As String
            Get
                Return ResourceManager.GetString("stromboli0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Roni.
        '''</summary>
        Friend Shared ReadOnly Property stromboli1() As String
            Get
                Return ResourceManager.GetString("stromboli1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mozzarella, pepperoni.
        '''</summary>
        Friend Shared ReadOnly Property stromboli1d() As String
            Get
                Return ResourceManager.GetString("stromboli1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vegetal.
        '''</summary>
        Friend Shared ReadOnly Property stromboli2() As String
            Get
                Return ResourceManager.GetString("stromboli2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spinach, tomato, mushroom, garlic, mozzarella.
        '''</summary>
        Friend Shared ReadOnly Property stromboli2d() As String
            Get
                Return ResourceManager.GetString("stromboli2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pollo Buffalo.
        '''</summary>
        Friend Shared ReadOnly Property stromboli3() As String
            Get
                Return ResourceManager.GetString("stromboli3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to roasted chicken, mozzarella, bleu cheese, buffalo sauce.
        '''</summary>
        Friend Shared ReadOnly Property stromboli3d() As String
            Get
                Return ResourceManager.GetString("stromboli3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CASA BOLI.
        '''</summary>
        Friend Shared ReadOnly Property stromboli4() As String
            Get
                Return ResourceManager.GetString("stromboli4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sausage, pepperoni, bacon, pepper, onions, mozarella.
        '''</summary>
        Friend Shared ReadOnly Property stromboli4d() As String
            Get
                Return ResourceManager.GetString("stromboli4d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Construye tu propio Stromboli.
        '''</summary>
        Friend Shared ReadOnly Property stromboli5() As String
            Get
                Return ResourceManager.GetString("stromboli5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to choose up to 4 toppings.
        '''</summary>
        Friend Shared ReadOnly Property stromboli5d() As String
            Get
                Return ResourceManager.GetString("stromboli5d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10.99.
        '''</summary>
        Friend Shared ReadOnly Property stromboliprice() As String
            Get
                Return ResourceManager.GetString("stromboliprice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hemos implementado un recargo del 3% para ayudar a pagar los costos de aumento asociados con los mandatos nuevos y crecientes del gobierno estatal y local. Si tiene alguna pregunta sobre este cargo, solicite hablar con un gerente. Gracias..
        '''</summary>
        Friend Shared ReadOnly Property surcharge() As String
            Get
                Return ResourceManager.GetString("surcharge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PIZZA POR LA REBANADA | BARRA COMPLETA.
        '''</summary>
        Friend Shared ReadOnly Property title() As String
            Get
                Return ResourceManager.GetString("title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PLACAS, SERVILLETAS Y UTENSILIOS DISPONIBLES A PETICIÓN.
        '''</summary>
        Friend Shared ReadOnly Property utensils() As String
            Get
                Return ResourceManager.GetString("utensils", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to jalapeño.
        '''</summary>
        Friend Shared ReadOnly Property veggie1() As String
            Get
                Return ResourceManager.GetString("veggie1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Espinacas.
        '''</summary>
        Friend Shared ReadOnly Property veggie10() As String
            Get
                Return ResourceManager.GetString("veggie10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie10price() As String
            Get
                Return ResourceManager.GetString("veggie10price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to albahaca.
        '''</summary>
        Friend Shared ReadOnly Property veggie11() As String
            Get
                Return ResourceManager.GetString("veggie11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie11price() As String
            Get
                Return ResourceManager.GetString("veggie11price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie1price() As String
            Get
                Return ResourceManager.GetString("veggie1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to piña.
        '''</summary>
        Friend Shared ReadOnly Property veggie2() As String
            Get
                Return ResourceManager.GetString("veggie2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie2price() As String
            Get
                Return ResourceManager.GetString("veggie2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pimiento verde.
        '''</summary>
        Friend Shared ReadOnly Property veggie3() As String
            Get
                Return ResourceManager.GetString("veggie3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie3price() As String
            Get
                Return ResourceManager.GetString("veggie3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to cebollas.
        '''</summary>
        Friend Shared ReadOnly Property veggie4() As String
            Get
                Return ResourceManager.GetString("veggie4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie4price() As String
            Get
                Return ResourceManager.GetString("veggie4price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pimienta de plátano.
        '''</summary>
        Friend Shared ReadOnly Property veggie5() As String
            Get
                Return ResourceManager.GetString("veggie5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie5price() As String
            Get
                Return ResourceManager.GetString("veggie5price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to aceituna.
        '''</summary>
        Friend Shared ReadOnly Property veggie6() As String
            Get
                Return ResourceManager.GetString("veggie6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie6price() As String
            Get
                Return ResourceManager.GetString("veggie6price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tomate.
        '''</summary>
        Friend Shared ReadOnly Property veggie7() As String
            Get
                Return ResourceManager.GetString("veggie7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie7price() As String
            Get
                Return ResourceManager.GetString("veggie7price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to seta.
        '''</summary>
        Friend Shared ReadOnly Property veggie8() As String
            Get
                Return ResourceManager.GetString("veggie8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie8price() As String
            Get
                Return ResourceManager.GetString("veggie8price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ajo.
        '''</summary>
        Friend Shared ReadOnly Property veggie9() As String
            Get
                Return ResourceManager.GetString("veggie9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie9price() As String
            Get
                Return ResourceManager.GetString("veggie9price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VEGETALES.
        '''</summary>
        Friend Shared ReadOnly Property veggies0() As String
            Get
                Return ResourceManager.GetString("veggies0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PASTELES BLANCOS.
        '''</summary>
        Friend Shared ReadOnly Property whitePies0() As String
            Get
                Return ResourceManager.GetString("whitePies0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pollo BBQ.
        '''</summary>
        Friend Shared ReadOnly Property whitePies1() As String
            Get
                Return ResourceManager.GetString("whitePies1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pollo asado, cebolla roja, salsa de barbacoa.
        '''</summary>
        Friend Shared ReadOnly Property whitePies1d() As String
            Get
                Return ResourceManager.GetString("whitePies1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mi pastel.
        '''</summary>
        Friend Shared ReadOnly Property whitePies2() As String
            Get
                Return ResourceManager.GetString("whitePies2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pepperoni, salsa de pesto, mozzarella, ricotta.
        '''</summary>
        Friend Shared ReadOnly Property whitePies2d() As String
            Get
                Return ResourceManager.GetString("whitePies2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Espinacas.
        '''</summary>
        Friend Shared ReadOnly Property whitePies3() As String
            Get
                Return ResourceManager.GetString("whitePies3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ajo fresco, espinacas, queso parmesano, mozzarella, ricotta.
        '''</summary>
        Friend Shared ReadOnly Property whitePies3d() As String
            Get
                Return ResourceManager.GetString("whitePies3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Florentino.
        '''</summary>
        Friend Shared ReadOnly Property whitePies4() As String
            Get
                Return ResourceManager.GetString("whitePies4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to espinaca fresca, tomate, ajo, parmesano, ricota, mozzarella.
        '''</summary>
        Friend Shared ReadOnly Property whitePies4d() As String
            Get
                Return ResourceManager.GetString("whitePies4d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pollo Buffalo.
        '''</summary>
        Friend Shared ReadOnly Property whitePies5() As String
            Get
                Return ResourceManager.GetString("whitePies5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pollo asado, mozzarella, queso bleu, salsa de rancho de búfalo.
        '''</summary>
        Friend Shared ReadOnly Property whitePies5d() As String
            Get
                Return ResourceManager.GetString("whitePies5d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Margherita.
        '''</summary>
        Friend Shared ReadOnly Property whitePies6() As String
            Get
                Return ResourceManager.GetString("whitePies6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tomate, ajo fresco, albahaca, mozzarella.
        '''</summary>
        Friend Shared ReadOnly Property whitePies6d() As String
            Get
                Return ResourceManager.GetString("whitePies6d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El Shroom.
        '''</summary>
        Friend Shared ReadOnly Property whitePies7() As String
            Get
                Return ResourceManager.GetString("whitePies7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to seta, ajo fresco, mozzarella, queso ricotta.
        '''</summary>
        Friend Shared ReadOnly Property whitePies7d() As String
            Get
                Return ResourceManager.GetString("whitePies7d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CBR.
        '''</summary>
        Friend Shared ReadOnly Property whitePies8() As String
            Get
                Return ResourceManager.GetString("whitePies8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pollo, tocino, salsa de rancho y tomate cortado en cubitos.
        '''</summary>
        Friend Shared ReadOnly Property whitePies8d() As String
            Get
                Return ResourceManager.GetString("whitePies8d", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
