'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class fr_FR
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CS540_Group_Project.fr-FR", GetType(fr_FR).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ajouter du poulet rôti pour.
        '''</summary>
        Friend Shared ReadOnly Property addSalad() As String
            Get
                Return ResourceManager.GetString("addSalad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property addSaladprice() As String
            Get
                Return ResourceManager.GetString("addSaladprice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (3) for 3.50.
        '''</summary>
        Friend Shared ReadOnly Property app1price1() As String
            Get
                Return ResourceManager.GetString("app1price1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (6) for 6.99.
        '''</summary>
        Friend Shared ReadOnly Property app1price2() As String
            Get
                Return ResourceManager.GetString("app1price2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (12) for 13.50.
        '''</summary>
        Friend Shared ReadOnly Property app1price3() As String
            Get
                Return ResourceManager.GetString("app1price3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 8.99.
        '''</summary>
        Friend Shared ReadOnly Property app2price() As String
            Get
                Return ResourceManager.GetString("app2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 7.99.
        '''</summary>
        Friend Shared ReadOnly Property app3price() As String
            Get
                Return ResourceManager.GetString("app3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.99.
        '''</summary>
        Friend Shared ReadOnly Property app4price() As String
            Get
                Return ResourceManager.GetString("app4price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to APÉRITIFS.
        '''</summary>
        Friend Shared ReadOnly Property appetizer0() As String
            Get
                Return ResourceManager.GetString("appetizer0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Noeud D&apos;ail.
        '''</summary>
        Friend Shared ReadOnly Property appetizer1() As String
            Get
                Return ResourceManager.GetString("appetizer1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to servi avec sauce marinara.
        '''</summary>
        Friend Shared ReadOnly Property appetizer1d() As String
            Get
                Return ResourceManager.GetString("appetizer1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ailes Désossées.
        '''</summary>
        Friend Shared ReadOnly Property appetizer2() As String
            Get
                Return ResourceManager.GetString("appetizer2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tendres de poulet frits servis avec votre choix de sauce (doux, moyen, chaud, ail parmesan, barbecue, 
        '''framboise jalapeno, ail épicé, poivre citron).
        '''</summary>
        Friend Shared ReadOnly Property appetizer2d() As String
            Get
                Return ResourceManager.GetString("appetizer2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Boulettes de Viande.
        '''</summary>
        Friend Shared ReadOnly Property appetizer3() As String
            Get
                Return ResourceManager.GetString("appetizer3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fait maison avec sauce marinara.
        '''</summary>
        Friend Shared ReadOnly Property appetizer3d() As String
            Get
                Return ResourceManager.GetString("appetizer3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Frites.
        '''</summary>
        Friend Shared ReadOnly Property appetizer4() As String
            Get
                Return ResourceManager.GetString("appetizer4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to frites coupées frites assaisonnées, 
        '''servi avec du ketchup.
        '''</summary>
        Friend Shared ReadOnly Property appetizer4d() As String
            Get
                Return ResourceManager.GetString("appetizer4d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FROMAGE.
        '''</summary>
        Friend Shared ReadOnly Property cheese0() As String
            Get
                Return ResourceManager.GetString("cheese0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ricotta.
        '''</summary>
        Friend Shared ReadOnly Property cheese1() As String
            Get
                Return ResourceManager.GetString("cheese1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property cheese1price() As String
            Get
                Return ResourceManager.GetString("cheese1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to provolone.
        '''</summary>
        Friend Shared ReadOnly Property cheese2() As String
            Get
                Return ResourceManager.GetString("cheese2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property cheese2price() As String
            Get
                Return ResourceManager.GetString("cheese2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fromage bleu.
        '''</summary>
        Friend Shared ReadOnly Property cheese3() As String
            Get
                Return ResourceManager.GetString("cheese3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property cheese3price() As String
            Get
                Return ResourceManager.GetString("cheese3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fromage mozzarella supplémentaire.
        '''</summary>
        Friend Shared ReadOnly Property cheese4() As String
            Get
                Return ResourceManager.GetString("cheese4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property cheese4price() As String
            Get
                Return ResourceManager.GetString("cheese4price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fromage de chèvre.
        '''</summary>
        Friend Shared ReadOnly Property cheese5() As String
            Get
                Return ResourceManager.GetString("cheese5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property cheese5price() As String
            Get
                Return ResourceManager.GetString("cheese5price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CRÉEZ VOTRE PROPRE TARTE.
        '''</summary>
        Friend Shared ReadOnly Property createPizza() As String
            Get
                Return ResourceManager.GetString("createPizza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10 inch cheese pizza 9.99.
        '''</summary>
        Friend Shared ReadOnly Property createPizzaprice1() As String
            Get
                Return ResourceManager.GetString("createPizzaprice1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 18 inch cheese pizza 18.99.
        '''</summary>
        Friend Shared ReadOnly Property createPizzaprice2() As String
            Get
                Return ResourceManager.GetString("createPizzaprice2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MENU COMPLET SERVI DE | 
        '''LIVRAISON RAPIDE | 
        '''PIZZA SERVI TOUT LE JOUR.
        '''</summary>
        Friend Shared ReadOnly Property description() As String
            Get
                Return ResourceManager.GetString("description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5.99.
        '''</summary>
        Friend Shared ReadOnly Property desser1price() As String
            Get
                Return ResourceManager.GetString("desser1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DESSERTS.
        '''</summary>
        Friend Shared ReadOnly Property dessert0() As String
            Get
                Return ResourceManager.GetString("dessert0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flan au Fromage.
        '''</summary>
        Friend Shared ReadOnly Property dessert1() As String
            Get
                Return ResourceManager.GetString("dessert1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to garniture au fromage à la crème, croûte de biscuit graham.
        '''</summary>
        Friend Shared ReadOnly Property dessert1d() As String
            Get
                Return ResourceManager.GetString("dessert1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tarte au chocolat et à la mousse.
        '''</summary>
        Friend Shared ReadOnly Property dessert2() As String
            Get
                Return ResourceManager.GetString("dessert2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mousse au chocolat, crème fouettée, croûte de biscuits au chocolat.
        '''</summary>
        Friend Shared ReadOnly Property dessert2d() As String
            Get
                Return ResourceManager.GetString("dessert2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5.99.
        '''</summary>
        Friend Shared ReadOnly Property dessert2price() As String
            Get
                Return ResourceManager.GetString("dessert2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Brownie au fudge.
        '''</summary>
        Friend Shared ReadOnly Property dessert3() As String
            Get
                Return ResourceManager.GetString("dessert3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.99.
        '''</summary>
        Friend Shared ReadOnly Property dessert3price() As String
            Get
                Return ResourceManager.GetString("dessert3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DINERS.
        '''</summary>
        Friend Shared ReadOnly Property dinner0() As String
            Get
                Return ResourceManager.GetString("dinner0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tous les dîners servis avec 2 nœuds d&apos;ail.
        '''</summary>
        Friend Shared ReadOnly Property dinner0d() As String
            Get
                Return ResourceManager.GetString("dinner0d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poulet au Parmesan.
        '''</summary>
        Friend Shared ReadOnly Property dinner1() As String
            Get
                Return ResourceManager.GetString("dinner1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to garni de fromage mozzarella, servi avec des penne, dans notre sauce marinara maison, basilic frais, fromage parmesan.
        '''</summary>
        Friend Shared ReadOnly Property dinner1d() As String
            Get
                Return ResourceManager.GetString("dinner1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11.99.
        '''</summary>
        Friend Shared ReadOnly Property dinner1price() As String
            Get
                Return ResourceManager.GetString("dinner1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lasagne à la viande.
        '''</summary>
        Friend Shared ReadOnly Property dinner2() As String
            Get
                Return ResourceManager.GetString("dinner2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to préparé avec notre boulette de viande maison, ricotta saucisse, parmesan, cuit à la perfection!.
        '''</summary>
        Friend Shared ReadOnly Property dinner2d() As String
            Get
                Return ResourceManager.GetString("dinner2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11.99.
        '''</summary>
        Friend Shared ReadOnly Property dinner2price() As String
            Get
                Return ResourceManager.GetString("dinner2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Penne Pâtes.
        '''</summary>
        Friend Shared ReadOnly Property dinner3() As String
            Get
                Return ResourceManager.GetString("dinner3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to add 2 meatballs for $3.
        '''</summary>
        Friend Shared ReadOnly Property dinner3add() As String
            Get
                Return ResourceManager.GetString("dinner3add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sauce marinara maison, basilic frais, fromage parmesan.
        '''</summary>
        Friend Shared ReadOnly Property dinner3d() As String
            Get
                Return ResourceManager.GetString("dinner3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 8.99.
        '''</summary>
        Friend Shared ReadOnly Property dinner3price() As String
            Get
                Return ResourceManager.GetString("dinner3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Penne au Four avec Saucisse.
        '''</summary>
        Friend Shared ReadOnly Property dinner4() As String
            Get
                Return ResourceManager.GetString("dinner4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sauce marinara maison, basilic frais, fromage parmesan garni de mozzarella.
        '''</summary>
        Friend Shared ReadOnly Property dinner4d() As String
            Get
                Return ResourceManager.GetString("dinner4d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11.99.
        '''</summary>
        Friend Shared ReadOnly Property dinner4price() As String
            Get
                Return ResourceManager.GetString("dinner4price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BOISSONS.
        '''</summary>
        Friend Shared ReadOnly Property drink0() As String
            Get
                Return ResourceManager.GetString("drink0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Red Bull.
        '''</summary>
        Friend Shared ReadOnly Property drink1() As String
            Get
                Return ResourceManager.GetString("drink1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.99.
        '''</summary>
        Friend Shared ReadOnly Property drink1price() As String
            Get
                Return ResourceManager.GetString("drink1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zico L&apos;eau de Noix de Coco.
        '''</summary>
        Friend Shared ReadOnly Property drink2() As String
            Get
                Return ResourceManager.GetString("drink2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property drink2price() As String
            Get
                Return ResourceManager.GetString("drink2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eau en Bouteille.
        '''</summary>
        Friend Shared ReadOnly Property drink3() As String
            Get
                Return ResourceManager.GetString("drink3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.29.
        '''</summary>
        Friend Shared ReadOnly Property drink3price() As String
            Get
                Return ResourceManager.GetString("drink3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 20 oz soda.
        '''</summary>
        Friend Shared ReadOnly Property drink4() As String
            Get
                Return ResourceManager.GetString("drink4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.25.
        '''</summary>
        Friend Shared ReadOnly Property drink4prince() As String
            Get
                Return ResourceManager.GetString("drink4prince", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to vitamin water.
        '''</summary>
        Friend Shared ReadOnly Property drink5() As String
            Get
                Return ResourceManager.GetString("drink5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.29.
        '''</summary>
        Friend Shared ReadOnly Property drink5price() As String
            Get
                Return ResourceManager.GetString("drink5price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PROTÉINE.
        '''</summary>
        Friend Shared ReadOnly Property protein0() As String
            Get
                Return ResourceManager.GetString("protein0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pepperoni.
        '''</summary>
        Friend Shared ReadOnly Property protein1() As String
            Get
                Return ResourceManager.GetString("protein1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property protein1price() As String
            Get
                Return ResourceManager.GetString("protein1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to saucisse.
        '''</summary>
        Friend Shared ReadOnly Property protein2() As String
            Get
                Return ResourceManager.GetString("protein2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property protein2price() As String
            Get
                Return ResourceManager.GetString("protein2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to boulette de viande.
        '''</summary>
        Friend Shared ReadOnly Property protein3() As String
            Get
                Return ResourceManager.GetString("protein3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property protein3price() As String
            Get
                Return ResourceManager.GetString("protein3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to jambon.
        '''</summary>
        Friend Shared ReadOnly Property protein4() As String
            Get
                Return ResourceManager.GetString("protein4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property protein4price() As String
            Get
                Return ResourceManager.GetString("protein4price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to bacon.
        '''</summary>
        Friend Shared ReadOnly Property protein5() As String
            Get
                Return ResourceManager.GetString("protein5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property protein5price() As String
            Get
                Return ResourceManager.GetString("protein5price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to poulet grillé.
        '''</summary>
        Friend Shared ReadOnly Property protein6() As String
            Get
                Return ResourceManager.GetString("protein6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property protein6price() As String
            Get
                Return ResourceManager.GetString("protein6price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PATES ROUGES.
        '''</summary>
        Friend Shared ReadOnly Property redPies0() As String
            Get
                Return ResourceManager.GetString("redPies0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Les amoureux de la Viande.
        '''</summary>
        Friend Shared ReadOnly Property redPies1() As String
            Get
                Return ResourceManager.GetString("redPies1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mozzarella, pepperoni, 
        '''saucisse, bacon, jambon, boulette de viande.
        '''</summary>
        Friend Shared ReadOnly Property redPies1d() As String
            Get
                Return ResourceManager.GetString("redPies1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amoureux des Végétariens.
        '''</summary>
        Friend Shared ReadOnly Property redPies2() As String
            Get
                Return ResourceManager.GetString("redPies2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to épinard, poivre vert, tomate, mozzarella, champignon, oignon, olive, ail frais.
        '''</summary>
        Friend Shared ReadOnly Property redPies2d() As String
            Get
                Return ResourceManager.GetString("redPies2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hawaïen.
        '''</summary>
        Friend Shared ReadOnly Property redPies3() As String
            Get
                Return ResourceManager.GetString("redPies3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ananas, jambon, bacon, mozzarella.
        '''</summary>
        Friend Shared ReadOnly Property redPies3d() As String
            Get
                Return ResourceManager.GetString("redPies3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quatre Fromages.
        '''</summary>
        Friend Shared ReadOnly Property redPies4() As String
            Get
                Return ResourceManager.GetString("redPies4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to parmesan, mozzarella, provolone, ricotta.
        '''</summary>
        Friend Shared ReadOnly Property redPies4d() As String
            Get
                Return ResourceManager.GetString("redPies4d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La Spéciale de Ciro.
        '''</summary>
        Friend Shared ReadOnly Property redPies5() As String
            Get
                Return ResourceManager.GetString("redPies5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pepperoni, saucisse, champignon, poivre vert, oignon, fromage supplémentaire.
        '''</summary>
        Friend Shared ReadOnly Property redPies5d() As String
            Get
                Return ResourceManager.GetString("redPies5d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Roquette.
        '''</summary>
        Friend Shared ReadOnly Property salad1() As String
            Get
                Return ResourceManager.GetString("salad1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to raisin doré, noix confite, tomate cerise, fromage de chèvre.
        '''</summary>
        Friend Shared ReadOnly Property salad1d() As String
            Get
                Return ResourceManager.GetString("salad1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5.99/10.00.
        '''</summary>
        Friend Shared ReadOnly Property salad1price() As String
            Get
                Return ResourceManager.GetString("salad1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to César
        '''.
        '''</summary>
        Friend Shared ReadOnly Property salad2() As String
            Get
                Return ResourceManager.GetString("salad2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to cœur de la romaine, croûtons, 
        '''parmesan rasé, vinaigrette césar classique.
        '''</summary>
        Friend Shared ReadOnly Property salad2d() As String
            Get
                Return ResourceManager.GetString("salad2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4.99/7.99.
        '''</summary>
        Friend Shared ReadOnly Property salad2price() As String
            Get
                Return ResourceManager.GetString("salad2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verts Mélangés.
        '''</summary>
        Friend Shared ReadOnly Property salad3() As String
            Get
                Return ResourceManager.GetString("salad3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to verts mélangés, tomate, olive noire, poivre vert, 
        '''oignon.
        '''</summary>
        Friend Shared ReadOnly Property salad3d() As String
            Get
                Return ResourceManager.GetString("salad3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4.99/7.99.
        '''</summary>
        Friend Shared ReadOnly Property salad3price() As String
            Get
                Return ResourceManager.GetString("salad3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SALADES.
        '''</summary>
        Friend Shared ReadOnly Property salads0() As String
            Get
                Return ResourceManager.GetString("salads0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (petit/grand).
        '''</summary>
        Friend Shared ReadOnly Property saladSize() As String
            Get
                Return ResourceManager.GetString("saladSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SAUCE.
        '''</summary>
        Friend Shared ReadOnly Property sauce0() As String
            Get
                Return ResourceManager.GetString("sauce0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to rouge.
        '''</summary>
        Friend Shared ReadOnly Property sauce1() As String
            Get
                Return ResourceManager.GetString("sauce1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pesto.
        '''</summary>
        Friend Shared ReadOnly Property sauce2() As String
            Get
                Return ResourceManager.GetString("sauce2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 7.99.
        '''</summary>
        Friend Shared ReadOnly Property sginatureSub1price() As String
            Get
                Return ResourceManager.GetString("sginatureSub1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property sginatureSub2price() As String
            Get
                Return ResourceManager.GetString("sginatureSub2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property sginatureSub3price() As String
            Get
                Return ResourceManager.GetString("sginatureSub3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SANDWICHS SIGNATURE.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub0() As String
            Get
                Return ResourceManager.GetString("signatureSub0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Steak au Fromage.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub1() As String
            Get
                Return ResourceManager.GetString("signatureSub1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to notre cheesesteak comprend un steak grillé de qualité supérieure, fromage américain blanc fondu, ajouter des champignons, des oignons ou des piments pour $0.25 chacun pour pimenter!.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub1d() As String
            Get
                Return ResourceManager.GetString("signatureSub1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poulet au Parmesan.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub2() As String
            Get
                Return ResourceManager.GetString("signatureSub2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to poulet pané maison, fromage mozzarella, 
        '''parmesan râpé, sauce marinara.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub2d() As String
            Get
                Return ResourceManager.GetString("signatureSub2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Boulette de Viande au Parmesan.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub3() As String
            Get
                Return ResourceManager.GetString("signatureSub3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to notre recette de boulettes de viande maison signature, garni de fromage mozzarella, 
        '''parmesan râpé, sauce marinara.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub3d() As String
            Get
                Return ResourceManager.GetString("signatureSub3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10 inch 11.99.
        '''</summary>
        Friend Shared ReadOnly Property specialtyPizzaprice1() As String
            Get
                Return ResourceManager.GetString("specialtyPizzaprice1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 18 inch 23.99.
        '''</summary>
        Friend Shared ReadOnly Property specialtyPizzaprice2() As String
            Get
                Return ResourceManager.GetString("specialtyPizzaprice2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PIZZAS SPÉCIALISÉES.
        '''</summary>
        Friend Shared ReadOnly Property specialtyPizzas() As String
            Get
                Return ResourceManager.GetString("specialtyPizzas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to STROMBOLI.
        '''</summary>
        Friend Shared ReadOnly Property stromboli0() As String
            Get
                Return ResourceManager.GetString("stromboli0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Roni.
        '''</summary>
        Friend Shared ReadOnly Property stromboli1() As String
            Get
                Return ResourceManager.GetString("stromboli1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mozzarella, pepperoni.
        '''</summary>
        Friend Shared ReadOnly Property stromboli1d() As String
            Get
                Return ResourceManager.GetString("stromboli1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Des légumes.
        '''</summary>
        Friend Shared ReadOnly Property stromboli2() As String
            Get
                Return ResourceManager.GetString("stromboli2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to épinard, tomate, champignon, ail, mozzarella.
        '''</summary>
        Friend Shared ReadOnly Property stromboli2d() As String
            Get
                Return ResourceManager.GetString("stromboli2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poulet Buffalo.
        '''</summary>
        Friend Shared ReadOnly Property stromboli3() As String
            Get
                Return ResourceManager.GetString("stromboli3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to poulet rôti, mozzarella, fromage bleu, sauce au bison.
        '''</summary>
        Friend Shared ReadOnly Property stromboli3d() As String
            Get
                Return ResourceManager.GetString("stromboli3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MAISON BOLI.
        '''</summary>
        Friend Shared ReadOnly Property stromboli4() As String
            Get
                Return ResourceManager.GetString("stromboli4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to saucisse, pepperoni, bacon, poivrons, oignons, mozzarella.
        '''</summary>
        Friend Shared ReadOnly Property stromboli4d() As String
            Get
                Return ResourceManager.GetString("stromboli4d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Construisez votre propre Boli.
        '''</summary>
        Friend Shared ReadOnly Property stromboli5() As String
            Get
                Return ResourceManager.GetString("stromboli5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to choisissez jusqu&apos;à 4 garnitures.
        '''</summary>
        Friend Shared ReadOnly Property stromboli5d() As String
            Get
                Return ResourceManager.GetString("stromboli5d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10.99.
        '''</summary>
        Friend Shared ReadOnly Property stromboliprice() As String
            Get
                Return ResourceManager.GetString("stromboliprice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nous avons mis en place une surtaxe de 3% pour aider à payer l&apos;augmentation des coûts associés aux nouveaux mandats de l&apos;État et des administrations locales, qui ne cessent de croître. Si vous avez des questions à propos de cette taxe s&apos;il vous plaît demander à parler à un gestionnaire. Merci.
        '''</summary>
        Friend Shared ReadOnly Property surcharge() As String
            Get
                Return ResourceManager.GetString("surcharge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property title() As String
            Get
                Return ResourceManager.GetString("title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PLAQUES, SERVIETTES ET USTENSILES SONT DISPONIBLES SUR DEMANDE.
        '''</summary>
        Friend Shared ReadOnly Property utensils() As String
            Get
                Return ResourceManager.GetString("utensils", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ananas.
        '''</summary>
        Friend Shared ReadOnly Property veggie1() As String
            Get
                Return ResourceManager.GetString("veggie1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to épinard.
        '''</summary>
        Friend Shared ReadOnly Property veggie10() As String
            Get
                Return ResourceManager.GetString("veggie10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie10price() As String
            Get
                Return ResourceManager.GetString("veggie10price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to basilic.
        '''</summary>
        Friend Shared ReadOnly Property veggie11() As String
            Get
                Return ResourceManager.GetString("veggie11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie11price() As String
            Get
                Return ResourceManager.GetString("veggie11price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie1price() As String
            Get
                Return ResourceManager.GetString("veggie1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pineapple.
        '''</summary>
        Friend Shared ReadOnly Property veggie2() As String
            Get
                Return ResourceManager.GetString("veggie2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie2price() As String
            Get
                Return ResourceManager.GetString("veggie2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to poivre vert.
        '''</summary>
        Friend Shared ReadOnly Property veggie3() As String
            Get
                Return ResourceManager.GetString("veggie3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie3price() As String
            Get
                Return ResourceManager.GetString("veggie3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to onions.
        '''</summary>
        Friend Shared ReadOnly Property veggie4() As String
            Get
                Return ResourceManager.GetString("veggie4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie4price() As String
            Get
                Return ResourceManager.GetString("veggie4price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to poivre de banane.
        '''</summary>
        Friend Shared ReadOnly Property veggie5() As String
            Get
                Return ResourceManager.GetString("veggie5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie5price() As String
            Get
                Return ResourceManager.GetString("veggie5price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to olive.
        '''</summary>
        Friend Shared ReadOnly Property veggie6() As String
            Get
                Return ResourceManager.GetString("veggie6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie6price() As String
            Get
                Return ResourceManager.GetString("veggie6price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tomate.
        '''</summary>
        Friend Shared ReadOnly Property veggie7() As String
            Get
                Return ResourceManager.GetString("veggie7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie7price() As String
            Get
                Return ResourceManager.GetString("veggie7price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to champignon.
        '''</summary>
        Friend Shared ReadOnly Property veggie8() As String
            Get
                Return ResourceManager.GetString("veggie8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie8price() As String
            Get
                Return ResourceManager.GetString("veggie8price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ail.
        '''</summary>
        Friend Shared ReadOnly Property veggie9() As String
            Get
                Return ResourceManager.GetString("veggie9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie9price() As String
            Get
                Return ResourceManager.GetString("veggie9price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DES LÉGUMES.
        '''</summary>
        Friend Shared ReadOnly Property veggies0() As String
            Get
                Return ResourceManager.GetString("veggies0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PÂTES BLANCHES.
        '''</summary>
        Friend Shared ReadOnly Property whitePies0() As String
            Get
                Return ResourceManager.GetString("whitePies0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poulet BBQ.
        '''</summary>
        Friend Shared ReadOnly Property whitePies1() As String
            Get
                Return ResourceManager.GetString("whitePies1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to poulet grillé, oignon rouge, sauce barbecue.
        '''</summary>
        Friend Shared ReadOnly Property whitePies1d() As String
            Get
                Return ResourceManager.GetString("whitePies1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ma tarte.
        '''</summary>
        Friend Shared ReadOnly Property whitePies2() As String
            Get
                Return ResourceManager.GetString("whitePies2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pepperoni, sauce pesto, mozzarella, ricotta.
        '''</summary>
        Friend Shared ReadOnly Property whitePies2d() As String
            Get
                Return ResourceManager.GetString("whitePies2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Épinard.
        '''</summary>
        Friend Shared ReadOnly Property whitePies3() As String
            Get
                Return ResourceManager.GetString("whitePies3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ail frais, épinard, parmesan, mozzarella, ricotta.
        '''</summary>
        Friend Shared ReadOnly Property whitePies3d() As String
            Get
                Return ResourceManager.GetString("whitePies3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Florentin.
        '''</summary>
        Friend Shared ReadOnly Property whitePies4() As String
            Get
                Return ResourceManager.GetString("whitePies4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to épinards frais, tomate, ail, parmesan, ricotta, mozzarella.
        '''</summary>
        Friend Shared ReadOnly Property whitePies4d() As String
            Get
                Return ResourceManager.GetString("whitePies4d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poulet Buffalo.
        '''</summary>
        Friend Shared ReadOnly Property whitePies5() As String
            Get
                Return ResourceManager.GetString("whitePies5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to poulet grillé, mozzarella, fromage bleu, sauce de ranch buffle .
        '''</summary>
        Friend Shared ReadOnly Property whitePies5d() As String
            Get
                Return ResourceManager.GetString("whitePies5d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Margherita.
        '''</summary>
        Friend Shared ReadOnly Property whitePies6() As String
            Get
                Return ResourceManager.GetString("whitePies6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tomate, ail frais, basilic, mozzarella.
        '''</summary>
        Friend Shared ReadOnly Property whitePies6d() As String
            Get
                Return ResourceManager.GetString("whitePies6d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le Champignon.
        '''</summary>
        Friend Shared ReadOnly Property whitePies7() As String
            Get
                Return ResourceManager.GetString("whitePies7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mushroom, ail frais, mozzarella, fromage ricotta.
        '''</summary>
        Friend Shared ReadOnly Property whitePies7d() As String
            Get
                Return ResourceManager.GetString("whitePies7d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CBR.
        '''</summary>
        Friend Shared ReadOnly Property whitePies8() As String
            Get
                Return ResourceManager.GetString("whitePies8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to poulet, bacon, vinaigrette ranch &amp; tomate en dé.
        '''</summary>
        Friend Shared ReadOnly Property whitePies8d() As String
            Get
                Return ResourceManager.GetString("whitePies8d", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
