'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class zh_CHT
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CS540_Group_Project.zh-CHT", GetType(zh_CHT).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 加烤雞肉.
        '''</summary>
        Friend Shared ReadOnly Property addSalad() As String
            Get
                Return ResourceManager.GetString("addSalad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property addSaladprice() As String
            Get
                Return ResourceManager.GetString("addSaladprice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (3) 個 3.50.
        '''</summary>
        Friend Shared ReadOnly Property app1price1() As String
            Get
                Return ResourceManager.GetString("app1price1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (6) 個 6.99.
        '''</summary>
        Friend Shared ReadOnly Property app1price2() As String
            Get
                Return ResourceManager.GetString("app1price2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (12) 個 13.50.
        '''</summary>
        Friend Shared ReadOnly Property app1price3() As String
            Get
                Return ResourceManager.GetString("app1price3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 8.99.
        '''</summary>
        Friend Shared ReadOnly Property app2price() As String
            Get
                Return ResourceManager.GetString("app2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 7.99.
        '''</summary>
        Friend Shared ReadOnly Property app3price() As String
            Get
                Return ResourceManager.GetString("app3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.99.
        '''</summary>
        Friend Shared ReadOnly Property app4price() As String
            Get
                Return ResourceManager.GetString("app4price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 開胃菜.
        '''</summary>
        Friend Shared ReadOnly Property appetizer0() As String
            Get
                Return ResourceManager.GetString("appetizer0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 大蒜結.
        '''</summary>
        Friend Shared ReadOnly Property appetizer1() As String
            Get
                Return ResourceManager.GetString("appetizer1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 配上瑪麗娜醬.
        '''</summary>
        Friend Shared ReadOnly Property appetizer1d() As String
            Get
                Return ResourceManager.GetString("appetizer1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 無骨的翅膀.
        '''</summary>
        Friend Shared ReadOnly Property appetizer2() As String
            Get
                Return ResourceManager.GetString("appetizer2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 炸雞招標配上你最喜歡的醬汁 (溫和, 中味, 辣, 巴馬干酪大蒜, 燒烤, 覆盆子辣椒, 辣大蒜, 檸檬胡椒).
        '''</summary>
        Friend Shared ReadOnly Property appetizer2d() As String
            Get
                Return ResourceManager.GetString("appetizer2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 肉丸.
        '''</summary>
        Friend Shared ReadOnly Property appetizer3() As String
            Get
                Return ResourceManager.GetString("appetizer3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 自製配醬汁.
        '''</summary>
        Friend Shared ReadOnly Property appetizer3d() As String
            Get
                Return ResourceManager.GetString("appetizer3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 薯條.
        '''</summary>
        Friend Shared ReadOnly Property appetizer4() As String
            Get
                Return ResourceManager.GetString("appetizer4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 皺切薯條, 配番茄醬.
        '''</summary>
        Friend Shared ReadOnly Property appetizer4d() As String
            Get
                Return ResourceManager.GetString("appetizer4d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 起司.
        '''</summary>
        Friend Shared ReadOnly Property cheese0() As String
            Get
                Return ResourceManager.GetString("cheese0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 凝乳.
        '''</summary>
        Friend Shared ReadOnly Property cheese1() As String
            Get
                Return ResourceManager.GetString("cheese1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property cheese1price() As String
            Get
                Return ResourceManager.GetString("cheese1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 波蘿伏洛乾酪.
        '''</summary>
        Friend Shared ReadOnly Property cheese2() As String
            Get
                Return ResourceManager.GetString("cheese2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property cheese2price() As String
            Get
                Return ResourceManager.GetString("cheese2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 布盧奶酪.
        '''</summary>
        Friend Shared ReadOnly Property cheese3() As String
            Get
                Return ResourceManager.GetString("cheese3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property cheese3price() As String
            Get
                Return ResourceManager.GetString("cheese3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 加奶酪.
        '''</summary>
        Friend Shared ReadOnly Property cheese4() As String
            Get
                Return ResourceManager.GetString("cheese4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property cheese4price() As String
            Get
                Return ResourceManager.GetString("cheese4price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 山羊奶酪.
        '''</summary>
        Friend Shared ReadOnly Property cheese5() As String
            Get
                Return ResourceManager.GetString("cheese5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property cheese5price() As String
            Get
                Return ResourceManager.GetString("cheese5price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 創建你自己的派.
        '''</summary>
        Friend Shared ReadOnly Property createPizza() As String
            Get
                Return ResourceManager.GetString("createPizza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 十英寸披薩 9.99.
        '''</summary>
        Friend Shared ReadOnly Property createPizzaprice1() As String
            Get
                Return ResourceManager.GetString("createPizzaprice1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 十八英寸披薩18.99.
        '''</summary>
        Friend Shared ReadOnly Property createPizzaprice2() As String
            Get
                Return ResourceManager.GetString("createPizzaprice2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 完整的菜單服務從上午十一點到晚上九點 | 交貨快
        ''' | 披薩每天服務.
        '''</summary>
        Friend Shared ReadOnly Property description() As String
            Get
                Return ResourceManager.GetString("description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5.99.
        '''</summary>
        Friend Shared ReadOnly Property desser1price() As String
            Get
                Return ResourceManager.GetString("desser1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 甜點.
        '''</summary>
        Friend Shared ReadOnly Property dessert0() As String
            Get
                Return ResourceManager.GetString("dessert0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 乳酪蛋糕.
        '''</summary>
        Friend Shared ReadOnly Property dessert1() As String
            Get
                Return ResourceManager.GetString("dessert1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 奶油芝士餡, 餅乾地殼.
        '''</summary>
        Friend Shared ReadOnly Property dessert1d() As String
            Get
                Return ResourceManager.GetString("dessert1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 巧克力慕斯派.
        '''</summary>
        Friend Shared ReadOnly Property dessert2() As String
            Get
                Return ResourceManager.GetString("dessert2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 巧克力慕斯, 鮮奶油, 巧克力餅乾.
        '''</summary>
        Friend Shared ReadOnly Property dessert2d() As String
            Get
                Return ResourceManager.GetString("dessert2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5.99.
        '''</summary>
        Friend Shared ReadOnly Property dessert2price() As String
            Get
                Return ResourceManager.GetString("dessert2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 福吉布朗尼.
        '''</summary>
        Friend Shared ReadOnly Property dessert3() As String
            Get
                Return ResourceManager.GetString("dessert3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.99.
        '''</summary>
        Friend Shared ReadOnly Property dessert3price() As String
            Get
                Return ResourceManager.GetString("dessert3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 晚餐.
        '''</summary>
        Friend Shared ReadOnly Property dinner0() As String
            Get
                Return ResourceManager.GetString("dinner0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 晚餐加兩個大蒜結.
        '''</summary>
        Friend Shared ReadOnly Property dinner0d() As String
            Get
                Return ResourceManager.GetString("dinner0d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 雞巴馬干酪.
        '''</summary>
        Friend Shared ReadOnly Property dinner1() As String
            Get
                Return ResourceManager.GetString("dinner1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 配上奶酪, 配上通心粉面食, 自製的瑪麗娜醬汁, 新鮮羅勒, 帕爾馬干酪.
        '''</summary>
        Friend Shared ReadOnly Property dinner1d() As String
            Get
                Return ResourceManager.GetString("dinner1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11.99.
        '''</summary>
        Friend Shared ReadOnly Property dinner1price() As String
            Get
                Return ResourceManager.GetString("dinner1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 肉烤寬麵條.
        '''</summary>
        Friend Shared ReadOnly Property dinner2() As String
            Get
                Return ResourceManager.GetString("dinner2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 加我們的自製肉丸, 香腸, 奶酪, 帕爾馬干酪, 烤到完美!.
        '''</summary>
        Friend Shared ReadOnly Property dinner2d() As String
            Get
                Return ResourceManager.GetString("dinner2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11.99.
        '''</summary>
        Friend Shared ReadOnly Property dinner2price() As String
            Get
                Return ResourceManager.GetString("dinner2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 意大利管面
        '''.
        '''</summary>
        Friend Shared ReadOnly Property dinner3() As String
            Get
                Return ResourceManager.GetString("dinner3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 加兩個肉丸 $3.
        '''</summary>
        Friend Shared ReadOnly Property dinner3add() As String
            Get
                Return ResourceManager.GetString("dinner3add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 自製意大利西紅柿醬, 新鮮羅勒, 帕爾馬干酪.
        '''</summary>
        Friend Shared ReadOnly Property dinner3d() As String
            Get
                Return ResourceManager.GetString("dinner3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 8.99.
        '''</summary>
        Friend Shared ReadOnly Property dinner3price() As String
            Get
                Return ResourceManager.GetString("dinner3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 烤通心粉加香腸.
        '''</summary>
        Friend Shared ReadOnly Property dinner4() As String
            Get
                Return ResourceManager.GetString("dinner4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 自製意大利西紅柿醬, 新鮮羅勒, 凝乳, 帕爾馬干酪加上奶酪.
        '''</summary>
        Friend Shared ReadOnly Property dinner4d() As String
            Get
                Return ResourceManager.GetString("dinner4d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11.99.
        '''</summary>
        Friend Shared ReadOnly Property dinner4price() As String
            Get
                Return ResourceManager.GetString("dinner4price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 飲料.
        '''</summary>
        Friend Shared ReadOnly Property drink0() As String
            Get
                Return ResourceManager.GetString("drink0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 紅牛.
        '''</summary>
        Friend Shared ReadOnly Property drink1() As String
            Get
                Return ResourceManager.GetString("drink1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.99.
        '''</summary>
        Friend Shared ReadOnly Property drink1price() As String
            Get
                Return ResourceManager.GetString("drink1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 椰子水.
        '''</summary>
        Friend Shared ReadOnly Property drink2() As String
            Get
                Return ResourceManager.GetString("drink2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property drink2price() As String
            Get
                Return ResourceManager.GetString("drink2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 瓶裝水.
        '''</summary>
        Friend Shared ReadOnly Property drink3() As String
            Get
                Return ResourceManager.GetString("drink3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.29.
        '''</summary>
        Friend Shared ReadOnly Property drink3price() As String
            Get
                Return ResourceManager.GetString("drink3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 二十盎司氣水.
        '''</summary>
        Friend Shared ReadOnly Property drink4() As String
            Get
                Return ResourceManager.GetString("drink4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.25.
        '''</summary>
        Friend Shared ReadOnly Property drink4prince() As String
            Get
                Return ResourceManager.GetString("drink4prince", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 維生素水.
        '''</summary>
        Friend Shared ReadOnly Property drink5() As String
            Get
                Return ResourceManager.GetString("drink5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.29.
        '''</summary>
        Friend Shared ReadOnly Property drink5price() As String
            Get
                Return ResourceManager.GetString("drink5price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 蛋白.
        '''</summary>
        Friend Shared ReadOnly Property protein0() As String
            Get
                Return ResourceManager.GetString("protein0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 意大利辣味香腸.
        '''</summary>
        Friend Shared ReadOnly Property protein1() As String
            Get
                Return ResourceManager.GetString("protein1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property protein1price() As String
            Get
                Return ResourceManager.GetString("protein1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 香腸.
        '''</summary>
        Friend Shared ReadOnly Property protein2() As String
            Get
                Return ResourceManager.GetString("protein2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property protein2price() As String
            Get
                Return ResourceManager.GetString("protein2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 肉丸.
        '''</summary>
        Friend Shared ReadOnly Property protein3() As String
            Get
                Return ResourceManager.GetString("protein3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property protein3price() As String
            Get
                Return ResourceManager.GetString("protein3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 火腿.
        '''</summary>
        Friend Shared ReadOnly Property protein4() As String
            Get
                Return ResourceManager.GetString("protein4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property protein4price() As String
            Get
                Return ResourceManager.GetString("protein4price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 培根.
        '''</summary>
        Friend Shared ReadOnly Property protein5() As String
            Get
                Return ResourceManager.GetString("protein5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property protein5price() As String
            Get
                Return ResourceManager.GetString("protein5price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 烤雞.
        '''</summary>
        Friend Shared ReadOnly Property protein6() As String
            Get
                Return ResourceManager.GetString("protein6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property protein6price() As String
            Get
                Return ResourceManager.GetString("protein6price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 番茄餡餅.
        '''</summary>
        Friend Shared ReadOnly Property redPies0() As String
            Get
                Return ResourceManager.GetString("redPies0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 肉愛好者.
        '''</summary>
        Friend Shared ReadOnly Property redPies1() As String
            Get
                Return ResourceManager.GetString("redPies1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 奶酪, 意大利辣味香腸, 香腸, 培根, 火腿, 肉丸.
        '''</summary>
        Friend Shared ReadOnly Property redPies1d() As String
            Get
                Return ResourceManager.GetString("redPies1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 素食愛好者.
        '''</summary>
        Friend Shared ReadOnly Property redPies2() As String
            Get
                Return ResourceManager.GetString("redPies2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 菠菜, 青椒, 番茄, 奶酪, 蘑菇, 洋蔥, 橄欖, 新鮮大蒜.
        '''</summary>
        Friend Shared ReadOnly Property redPies2d() As String
            Get
                Return ResourceManager.GetString("redPies2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 夏威夷.
        '''</summary>
        Friend Shared ReadOnly Property redPies3() As String
            Get
                Return ResourceManager.GetString("redPies3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 鳳梨, 火腿, 培根, 奶酪.
        '''</summary>
        Friend Shared ReadOnly Property redPies3d() As String
            Get
                Return ResourceManager.GetString("redPies3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 四個奶酪.
        '''</summary>
        Friend Shared ReadOnly Property redPies4() As String
            Get
                Return ResourceManager.GetString("redPies4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 帕爾馬干酪, 奶酪, 波蘿伏洛乾酪, 凝乳.
        '''</summary>
        Friend Shared ReadOnly Property redPies4d() As String
            Get
                Return ResourceManager.GetString("redPies4d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ciro&apos;s 的特別.
        '''</summary>
        Friend Shared ReadOnly Property redPies5() As String
            Get
                Return ResourceManager.GetString("redPies5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 意大利辣味香腸, 香腸,  蘑菇, 青椒, 洋蔥, 加奶酪.
        '''</summary>
        Friend Shared ReadOnly Property redPies5d() As String
            Get
                Return ResourceManager.GetString("redPies5d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 芝麻菜.
        '''</summary>
        Friend Shared ReadOnly Property salad1() As String
            Get
                Return ResourceManager.GetString("salad1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 金葡萄乾, 蜜餞核桃, 小番茄, 山羊奶酪.
        '''</summary>
        Friend Shared ReadOnly Property salad1d() As String
            Get
                Return ResourceManager.GetString("salad1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5.99/10.00.
        '''</summary>
        Friend Shared ReadOnly Property salad1price() As String
            Get
                Return ResourceManager.GetString("salad1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 凱撒.
        '''</summary>
        Friend Shared ReadOnly Property salad2() As String
            Get
                Return ResourceManager.GetString("salad2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 生菜, 麵包塊, 帕爾馬干酪, 凱撒醬.
        '''</summary>
        Friend Shared ReadOnly Property salad2d() As String
            Get
                Return ResourceManager.GetString("salad2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4.99/7.99.
        '''</summary>
        Friend Shared ReadOnly Property salad2price() As String
            Get
                Return ResourceManager.GetString("salad2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 沙拉.
        '''</summary>
        Friend Shared ReadOnly Property salad3() As String
            Get
                Return ResourceManager.GetString("salad3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 蔬菜, 番茄, 黑橄欖, 青椒, 洋蔥
        '''.
        '''</summary>
        Friend Shared ReadOnly Property salad3d() As String
            Get
                Return ResourceManager.GetString("salad3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4.99/7.99.
        '''</summary>
        Friend Shared ReadOnly Property salad3price() As String
            Get
                Return ResourceManager.GetString("salad3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 沙拉.
        '''</summary>
        Friend Shared ReadOnly Property salads0() As String
            Get
                Return ResourceManager.GetString("salads0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (小/大).
        '''</summary>
        Friend Shared ReadOnly Property saladSize() As String
            Get
                Return ResourceManager.GetString("saladSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 醬.
        '''</summary>
        Friend Shared ReadOnly Property sauce0() As String
            Get
                Return ResourceManager.GetString("sauce0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 番茄醬.
        '''</summary>
        Friend Shared ReadOnly Property sauce1() As String
            Get
                Return ResourceManager.GetString("sauce1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 香草醬.
        '''</summary>
        Friend Shared ReadOnly Property sauce2() As String
            Get
                Return ResourceManager.GetString("sauce2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 7.99.
        '''</summary>
        Friend Shared ReadOnly Property sginatureSub1price() As String
            Get
                Return ResourceManager.GetString("sginatureSub1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 三明治
        '''.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub0() As String
            Get
                Return ResourceManager.GetString("signatureSub0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 奶酪牛排.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub1() As String
            Get
                Return ResourceManager.GetString("signatureSub1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 我們的奶酪牛排包括烤牛排, 融化的美國奶酪 加蘑菇, 洋蔥, 或辣椒每個加0.25美分!.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub1d() As String
            Get
                Return ResourceManager.GetString("signatureSub1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 雞干酪.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub2() As String
            Get
                Return ResourceManager.GetString("signatureSub2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 自製雞肉, 奶酪, 帕爾馬干酪, 瑪麗娜醬.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub2d() As String
            Get
                Return ResourceManager.GetString("signatureSub2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 肉丸干酪.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub3() As String
            Get
                Return ResourceManager.GetString("signatureSub3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 我們的招牌肉丸配方, 配上奶酪, 干酪, 瑪麗娜醬.
        '''</summary>
        Friend Shared ReadOnly Property signatureSub3d() As String
            Get
                Return ResourceManager.GetString("signatureSub3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10 英寸 11.99.
        '''</summary>
        Friend Shared ReadOnly Property specialtyPizzaprice1() As String
            Get
                Return ResourceManager.GetString("specialtyPizzaprice1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 18 英寸 23.99.
        '''</summary>
        Friend Shared ReadOnly Property specialtyPizzaprice2() As String
            Get
                Return ResourceManager.GetString("specialtyPizzaprice2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 特色披薩.
        '''</summary>
        Friend Shared ReadOnly Property specialtyPizzas() As String
            Get
                Return ResourceManager.GetString("specialtyPizzas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 斯特龍博利
        '''.
        '''</summary>
        Friend Shared ReadOnly Property stromboli0() As String
            Get
                Return ResourceManager.GetString("stromboli0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 意大利辣味香腸.
        '''</summary>
        Friend Shared ReadOnly Property stromboli1() As String
            Get
                Return ResourceManager.GetString("stromboli1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 奶酪, 意大利辣味香腸.
        '''</summary>
        Friend Shared ReadOnly Property stromboli1d() As String
            Get
                Return ResourceManager.GetString("stromboli1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 蔬菜.
        '''</summary>
        Friend Shared ReadOnly Property stromboli2() As String
            Get
                Return ResourceManager.GetString("stromboli2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 菠菜, 番茄, 蘑菇, 大蒜, 奶酪.
        '''</summary>
        Friend Shared ReadOnly Property stromboli2d() As String
            Get
                Return ResourceManager.GetString("stromboli2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 水牛雞.
        '''</summary>
        Friend Shared ReadOnly Property stromboli3() As String
            Get
                Return ResourceManager.GetString("stromboli3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 烤雞, 奶酪, 布盧奶酪, 水牛醬.
        '''</summary>
        Friend Shared ReadOnly Property stromboli3d() As String
            Get
                Return ResourceManager.GetString("stromboli3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 家利辣味香腸.
        '''</summary>
        Friend Shared ReadOnly Property stromboli4() As String
            Get
                Return ResourceManager.GetString("stromboli4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 香腸, 意大利辣味香腸, 培根, 胡椒, 洋蔥, 奶酪.
        '''</summary>
        Friend Shared ReadOnly Property stromboli4d() As String
            Get
                Return ResourceManager.GetString("stromboli4d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 自製利辣味香腸.
        '''</summary>
        Friend Shared ReadOnly Property stromboli5() As String
            Get
                Return ResourceManager.GetString("stromboli5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 加上四個澆頭.
        '''</summary>
        Friend Shared ReadOnly Property stromboli5d() As String
            Get
                Return ResourceManager.GetString("stromboli5d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10.99.
        '''</summary>
        Friend Shared ReadOnly Property stromboliprice() As String
            Get
                Return ResourceManager.GetString("stromboliprice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 我們已經實施了三成收費幫助支付增加的成本伴隨著新的和不斷增長的州和地方政府的要求. 如果您對此費用有任何疑問，請詢問經理. 謝謝..
        '''</summary>
        Friend Shared ReadOnly Property surcharge() As String
            Get
                Return ResourceManager.GetString("surcharge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 切片披薩 | 完整酒吧.
        '''</summary>
        Friend Shared ReadOnly Property title() As String
            Get
                Return ResourceManager.GetString("title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 盤子, 餐巾, 和用具可根據要求提供.
        '''</summary>
        Friend Shared ReadOnly Property utensils() As String
            Get
                Return ResourceManager.GetString("utensils", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 辣椒.
        '''</summary>
        Friend Shared ReadOnly Property veggie1() As String
            Get
                Return ResourceManager.GetString("veggie1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 菠菜.
        '''</summary>
        Friend Shared ReadOnly Property veggie10() As String
            Get
                Return ResourceManager.GetString("veggie10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie10price() As String
            Get
                Return ResourceManager.GetString("veggie10price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 羅勒.
        '''</summary>
        Friend Shared ReadOnly Property veggie11() As String
            Get
                Return ResourceManager.GetString("veggie11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie11price() As String
            Get
                Return ResourceManager.GetString("veggie11price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie1price() As String
            Get
                Return ResourceManager.GetString("veggie1price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 鳳梨.
        '''</summary>
        Friend Shared ReadOnly Property veggie2() As String
            Get
                Return ResourceManager.GetString("veggie2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie2price() As String
            Get
                Return ResourceManager.GetString("veggie2price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 青椒.
        '''</summary>
        Friend Shared ReadOnly Property veggie3() As String
            Get
                Return ResourceManager.GetString("veggie3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie3price() As String
            Get
                Return ResourceManager.GetString("veggie3price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 洋蔥.
        '''</summary>
        Friend Shared ReadOnly Property veggie4() As String
            Get
                Return ResourceManager.GetString("veggie4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie4price() As String
            Get
                Return ResourceManager.GetString("veggie4price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 香蕉胡椒.
        '''</summary>
        Friend Shared ReadOnly Property veggie5() As String
            Get
                Return ResourceManager.GetString("veggie5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie5price() As String
            Get
                Return ResourceManager.GetString("veggie5price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 橄欖.
        '''</summary>
        Friend Shared ReadOnly Property veggie6() As String
            Get
                Return ResourceManager.GetString("veggie6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie6price() As String
            Get
                Return ResourceManager.GetString("veggie6price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 番茄.
        '''</summary>
        Friend Shared ReadOnly Property veggie7() As String
            Get
                Return ResourceManager.GetString("veggie7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie7price() As String
            Get
                Return ResourceManager.GetString("veggie7price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 蘑菇.
        '''</summary>
        Friend Shared ReadOnly Property veggie8() As String
            Get
                Return ResourceManager.GetString("veggie8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie8price() As String
            Get
                Return ResourceManager.GetString("veggie8price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 大蒜.
        '''</summary>
        Friend Shared ReadOnly Property veggie9() As String
            Get
                Return ResourceManager.GetString("veggie9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property veggie9price() As String
            Get
                Return ResourceManager.GetString("veggie9price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 蔬菜.
        '''</summary>
        Friend Shared ReadOnly Property veggies0() As String
            Get
                Return ResourceManager.GetString("veggies0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 白汁餡餅.
        '''</summary>
        Friend Shared ReadOnly Property whitePies0() As String
            Get
                Return ResourceManager.GetString("whitePies0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 燒烤雞.
        '''</summary>
        Friend Shared ReadOnly Property whitePies1() As String
            Get
                Return ResourceManager.GetString("whitePies1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 烤雞, 紅洋蔥, 烤肉醬.
        '''</summary>
        Friend Shared ReadOnly Property whitePies1d() As String
            Get
                Return ResourceManager.GetString("whitePies1d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 我的餡餅.
        '''</summary>
        Friend Shared ReadOnly Property whitePies2() As String
            Get
                Return ResourceManager.GetString("whitePies2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 意大利辣味香腸, 香草醬, 奶酪, 凝乳.
        '''</summary>
        Friend Shared ReadOnly Property whitePies2d() As String
            Get
                Return ResourceManager.GetString("whitePies2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 菠菜.
        '''</summary>
        Friend Shared ReadOnly Property whitePies3() As String
            Get
                Return ResourceManager.GetString("whitePies3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 新鮮大蒜, 菠菜, 帕爾馬干酪, 奶酪, 凝乳.
        '''</summary>
        Friend Shared ReadOnly Property whitePies3d() As String
            Get
                Return ResourceManager.GetString("whitePies3d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 佛羅倫薩.
        '''</summary>
        Friend Shared ReadOnly Property whitePies4() As String
            Get
                Return ResourceManager.GetString("whitePies4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 新鮮菠菜, 番茄, 大蒜, 帕爾馬干酪, 凝乳, 奶酪.
        '''</summary>
        Friend Shared ReadOnly Property whitePies4d() As String
            Get
                Return ResourceManager.GetString("whitePies4d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 水牛雞.
        '''</summary>
        Friend Shared ReadOnly Property whitePies5() As String
            Get
                Return ResourceManager.GetString("whitePies5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 烤雞, 奶酪, 布盧奶酪, 水牛牧場醬.
        '''</summary>
        Friend Shared ReadOnly Property whitePies5d() As String
            Get
                Return ResourceManager.GetString("whitePies5d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 瑪格麗塔.
        '''</summary>
        Friend Shared ReadOnly Property whitePies6() As String
            Get
                Return ResourceManager.GetString("whitePies6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 番茄, 新鮮大蒜, 羅勒, 奶酪.
        '''</summary>
        Friend Shared ReadOnly Property whitePies6d() As String
            Get
                Return ResourceManager.GetString("whitePies6d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 蘑菇.
        '''</summary>
        Friend Shared ReadOnly Property whitePies7() As String
            Get
                Return ResourceManager.GetString("whitePies7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 蘑菇, 新鮮大蒜, 奶酪, 凝乳.
        '''</summary>
        Friend Shared ReadOnly Property whitePies7d() As String
            Get
                Return ResourceManager.GetString("whitePies7d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 雞, 培根, 和牧場醬.
        '''</summary>
        Friend Shared ReadOnly Property whitePies8() As String
            Get
                Return ResourceManager.GetString("whitePies8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 雞, 培根, 牧場醬和番茄.
        '''</summary>
        Friend Shared ReadOnly Property whitePies8d() As String
            Get
                Return ResourceManager.GetString("whitePies8d", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
